resource "local_file" "outputs" {
  filename = "${path.module}/outputs.json"
  content = jsonencode({
    comments = "DO NOT MODIFY THIS FILE MANUALLY. IT IS AUTOGENERATED ON SUCCESSFUL TERRAFORM APPLY. MAKE ANY NECESSARY CHANGES IN localfile.tf"
    outputs = {
      tca_aws_current_region = {
        value = "${data.aws_region.current.name}"
      },
      # AppSync
      tca_appsync_graphql_api_region = {
        value = "${data.aws_region.current.name}"
      },
      tca_appsync_graphql_api_id = {
        value = "${aws_appsync_graphql_api.tca_appsync_graphql_api.id}"
      },
      tca_appsync_graphql_api_uris = {
        value = {
          GRAPHQL  = "${aws_appsync_graphql_api.tca_appsync_graphql_api.uris.GRAPHQL}",
          REALTIME = "${aws_appsync_graphql_api.tca_appsync_graphql_api.uris.REALTIME}"
        }
      },
      # Cognito
      tca_user_pool_region = {
        value = "${data.aws_region.current.name}"
      },
      tca_user_pool_id = {
        value = "${aws_cognito_user_pool.tca_user_pool.id}"
      },
      tca_user_pool_client_id = {
        value = "${aws_cognito_user_pool_client.tca_user_pool_client.id}"
      },
      tca_identity_pool_id = {
        value = "${aws_cognito_identity_pool.tca_identity_pool.id}"
      },
      # S3
      tca_landing_bucket = {
        value = "${aws_s3_bucket.tca_landing_bucket.id}"
      },
      tca_input_bucket = {
        value = "${aws_s3_bucket.tca_input_bucket.id}"
      },
      tca_output_bucket = {
        value = "${aws_s3_bucket.tca_output_bucket.id}"
      },
      tca_app_storage_bucket = {
        value = "${aws_s3_bucket.tca_app_storage_bucket.id}"
      },

    }
  })

  # -- ugly way of doing it --
  # content = <<-EOF
  # {
  #   "outputs": {
  #     "tca_appsync_graphql_api_region": {
  #       "value": "${data.aws_region.current.name}"
  #     },
  #     "tca_appsync_grapql_api_id": {
  #       "value": "${aws_appsync_graphql_api.tca_appsync_grapql_api.id}"
  #     },
  #     "tca_appsync_grapql_api_uris": {
  #       "value": {
  #        "GRAPHQL": "${aws_appsync_graphql_api.tca_appsync_grapql_api.uris.GRAPHQL}",
  #        "REALTIME": "${aws_appsync_graphql_api.tca_appsync_grapql_api.uris.REALTIME}"
  #       }
  #     },
  #     "tca_user_pool_region": {
  #       "value": "${data.aws_region.current.name}"
  #     },
  #     "tca_user_pool_id": {
  #       "value": "${aws_cognito_user_pool.tca_user_pool.id}"
  #     },
  #     "tca_user_pool_client": {
  #       "value": "${aws_cognito_user_pool_client.tca_user_pool_client.id}"
  #     },
  #     "tca_identity_pool_id": {
  #       "value": "${aws_cognito_identity_pool.tca_identity_pool.id}"
  #     },
  #     "tca_input_bucket": {
  #       "value": "${aws_s3_bucket.tca_input_bucket.id}"
  #     },
  #     "tca_output_bucket": {
  #       "value": "${aws_s3_bucket.tca_output_bucket.id}"
  #     },
  #     "tca_app_storage_bucket": {
  #       "value": "${aws_s3_bucket.tca_app_storage_bucket.id}"
  #     }
  #   }
  # }
  # EOF

  # -- previously used but has unneccessary data from tfstate --
  # source = "./terraform.tfstate.outputs" -- previously used but has unneccessary data
}



